name: macOS C Compile and Run Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run-on-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # gcc 명령어에 -DTEST_ENV 를 추가!
      - name: Compile the C code for testing
        run: gcc -DTEST_ENV -o MAKEPIC2 MAKEPIC2.c

      - name: Run the program with sample inputs
        run: |
          ./MAKEPIC2 <<EOF
          10
          10
          d
          d
          z
          1
          s
          y
          testfile
          q
          EOF

          
